CHANGE: Implemented RaspberryController for changing the state of the…
Team-Taucher/Smarthome pull request #3
Opened 2020-09-22 16:31 UTC by DaniloMurer

Change the state of the GPIO pins. This means putting or removing voltage from the selected pin.
Ready for Review
@Team-Taucher/backend

2020-09-25 08:13 UTC, stefanninkovic commented on src/Communication.Raspberry/RaspberryConnector.cs
> +        /// <param name="pinValue">Value of the pin</param>
parameter is redundant

2020-09-25 08:15 UTC, stefanninkovic requested changes
Method SetHigh contains redundant parameter-description. Also a "$" is in the XML-Documentation without context.

2020-09-28 19:00 UTC, stefanninkovic approved these changes

2020-09-28 19:02 UTC, whitehaven75 approved these changes

2020-09-28 19:02 UTC, merged